FROM python:3.10

WORKDIR /app
COPY . /app

RUN apt-get update && \
    apt-get install -y libjpeg-dev zlib1g-dev libpng-dev libtiff-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt

EXPOSE 5000
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:5000"]
